"""Word lists and code snippets for clitype."""

WORDS_ENGLISH = [
    "the", "be", "to", "of", "and", "a", "in", "that", "have", "i",
    "it", "for", "not", "on", "with", "he", "as", "you", "do", "at",
    "this", "but", "his", "by", "from", "they", "we", "her", "she", "or",
    "an", "will", "my", "one", "all", "would", "there", "their", "what", "so",
    "up", "out", "if", "about", "who", "get", "which", "go", "me", "when",
    "make", "can", "like", "time", "no", "just", "him", "know", "take", "people",
    "into", "year", "your", "good", "some", "could", "them", "see", "other", "than",
    "then", "now", "look", "only", "come", "its", "over", "think", "also", "back",
    "after", "use", "two", "how", "our", "work", "first", "well", "way", "even",
    "new", "want", "because", "any", "these", "give", "day", "most", "us", "great",
    "between", "need", "under", "each", "much", "right", "before", "too", "same", "mean",
    "where", "help", "through", "long", "thing", "own", "still", "find", "here", "old",
    "made", "world", "should", "call", "many", "around", "while", "last", "keep", "never",
    "say", "small", "every", "again", "thought", "went", "hand", "high", "part", "place",
    "very", "something", "life", "home", "might", "end", "start", "tell", "put", "left",
    "few", "began", "head", "kind", "next", "turn", "move", "live", "found", "both",
    "line", "play", "does", "point", "big", "change", "open", "close", "read", "run",
    "ask", "try", "set", "may", "let", "show", "best", "three", "often", "side",
    "down", "hold", "another", "off", "away", "house", "night", "water", "room", "stand",
    "state", "word", "late", "hard", "without", "though", "idea", "light", "child", "stop",
]

WORDS_INDONESIAN = [
    "dan", "yang", "di", "ini", "itu", "dengan", "untuk", "tidak", "dari", "pada",
    "ada", "akan", "saya", "anda", "kita", "mereka", "dia", "kami", "ke", "sudah",
    "bisa", "juga", "atau", "satu", "dua", "orang", "hari", "tahun", "waktu", "banyak",
    "besar", "lagi", "seperti", "harus", "semua", "belum", "baru", "sangat", "baik", "tahu",
    "mau", "masih", "lebih", "setelah", "sekarang", "dapat", "punya", "kalau", "antara", "oleh",
    "karena", "sebuah", "tentang", "sampai", "menjadi", "membuat", "kata", "pergi", "datang", "makan",
    "melihat", "kerja", "hidup", "rumah", "lama", "dunia", "anak", "nama", "tempat", "kecil",
    "tinggi", "lain", "cara", "beberapa", "setiap", "paling", "dalam", "tanpa", "sendiri", "teman",
    "air", "uang", "benar", "perlu", "boleh", "jalan", "bawah", "atas", "depan", "sering",
    "berapa", "dimana", "kapan", "kenapa", "siapa", "bagaimana", "selalu", "hanya", "sebelum", "terus",
    "sejak", "tinggal", "bicara", "bantu", "jadi", "cukup", "dekat", "jauh", "pagi", "siang",
    "malam", "sore", "minggu", "bulan", "pertama", "terakhir", "mungkin", "mulai", "ambil", "beri",
    "cari", "buat", "tulis", "baca", "dengar", "pikir", "tanya", "jawab", "tunggu", "buka",
    "tutup", "lari", "berjalan", "duduk", "berdiri", "tidur", "bangun", "minum", "masuk", "keluar",
    "beli", "jual", "pekerjaan", "keluarga", "sekolah", "kota", "negara", "bahasa", "makanan", "warna",
    "putih", "hitam", "merah", "biru", "kuning", "hijau", "senang", "sedih", "marah", "takut",
    "cantik", "tampan", "pintar", "bodoh", "cepat", "lambat", "mudah", "susah", "panas", "dingin",
    "berat", "ringan", "bersih", "kotor", "sedikit", "tua", "muda", "pendek", "panjang", "lebar",
    "sempit", "tebal", "tipis", "keras", "lembut", "manis", "asin", "pedas", "asam", "pahit",
    "toko", "pasar", "pantai", "gunung", "sungai", "pohon", "bunga", "hewan", "burung", "ikan",
]

CODE_SNIPPETS = [
    'def hello(name):\n    return f"Hello, {name}"',
    "const sum = (a, b) => a + b;",
    "for (int i = 0; i < n; i++) {",
    '<div class="container">',
    ".flex { display: flex; }",
    "if __name__ == '__main__':",
    "import os\nimport sys",
    "console.log('Hello, world!');",
    "printf(\"Hello, world!\\n\");",
    "def fibonacci(n):\n    if n <= 1:\n        return n",
    "let result = array.map(x => x * 2);",
    "struct Point {\n    int x;\n    int y;\n};",
    '<a href="https://example.com">Link</a>',
    "body { margin: 0; padding: 0; }",
    "class Dog:\n    def __init__(self, name):\n        self.name = name",
    "const fetchData = async () => {\n    const res = await fetch(url);\n};",
    "#include <stdio.h>\nint main() {",
    '<input type="text" placeholder="Enter name" />',
    ".grid { display: grid; gap: 1rem; }",
    "try:\n    result = int(value)\nexcept ValueError:",
    "function factorial(n) {\n    return n <= 1 ? 1 : n * factorial(n - 1);\n}",
    "while (ptr != NULL) {\n    ptr = ptr->next;\n}",
    "<ul>\n    <li>Item one</li>\n</ul>",
    "color: #333; font-size: 16px;",
    "with open('file.txt', 'r') as f:\n    data = f.read()",
    "document.getElementById('app');",
    "typedef unsigned long size_t;",
    '<img src="photo.jpg" alt="Photo" />',
    "@media (max-width: 768px) {\n    .sidebar { display: none; }\n}",
    "numbers = [x for x in range(10) if x % 2 == 0]",
    "const [count, setCount] = useState(0);",
    "malloc(sizeof(int) * n);",
    '<form action="/submit" method="post">',
    "transition: all 0.3s ease;",
]
